dist: trusty
sudo: false

language: ruby
cache: bundler

env:
  - NOMAD_VERSION=0.5.6
  - NOMAD_VERSION=0.4.1

before_install:
  - curl -sLo nomad.zip https://releases.hashicorp.com/nomad/${NOMAD_VERSION}/nomad_${NOMAD_VERSION}_linux_amd64.zip
  - unzip nomad.zip
  - mkdir ~/bin
  - mv nomad ~/bin
  - export PATH="~/bin:$PATH"

branches:
  only:
    - master

rvm:
  - 2.2
  - 2.3
  - 2.4
